// chapters/chapter_14/web/frontend/components/grid_component.tsx
import * as React from "react";

export class Container extends React.Component {
    public render() {
        return (
            <div className="container">
                {this.props.children}
            </div>
        );
    }
}

export class Row extends React.Component {
    public render() {
        return (
            <div className="row">
                {this.props.children}
            </div>
        );
    }
}

// In the bootstrap grid system the max size is 12
type ColumnWidth = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
type DeviceSize = "s" | "m" | "l" | "xl";

interface ColumnProps {
    width: ColumnWidth;
    size?: DeviceSize;
}

export class Column extends React.Component<ColumnProps> {
    public render() {
        return (
            <div className={this._getClass()}>
                {this.props.children}
            </div>
        );
    }
    private _getClass() {
        if (this.props.size !== undefined) {
            return `col-${this.props.size}-${this.props.width}`;
        } else {
            return `col-${this.props.width}`;
        }
    }
}

// chapters/chapter_15/web/frontend/components/grid.component.ts
/*
import { Component, Input } from "@angular/core";

@Component({
    selector: "",
    template: `
        <div class="container">
            {this.props.children}
        </div>
    `
})
export class Container {}

@Component({
    selector: "",
    template: `
        <div class="row">
            {this.props.children}
        </div>
    `
})
export class Row {}

// In the bootstrap grid system the max size is 12
type ColumnWidth = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
type DeviceSize = "s" | "m" | "l" | "xl";

@Component({
    selector: "",
    template: `
    <div [class]={class} [style]={style}>
        {this.props.children}
    </div>
    `
})
export class Column {
    @Input() public width!: ColumnWidth;
    @Input() public size?: DeviceSize;
    @Input() public style? = "";
    public get class() {
        if (this.size !== undefined) {
            return `col-${this.size}-${this.width}`;
        } else {
            return `col-${this.width}`;
        }
    }
}
*/
