// chapters/chapter_14/web/frontend/components/header_component.tsx
import { Route, Switch, BrowserRouter, Link } from "react-router-dom";
import * as React from "react";

type BgColor = "primary" | "secondary" | "success" |
               "danger" | "warning" | "info" | "light" |
               "dark" | "white";

interface HeaderProps {
    bg: BgColor;
    title: string;
    rootPath: string;
    links: { path: string; text: string }[];
}

export const Header = (props: HeaderProps) => (
    <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <Link className="navbar-brand" to={props.rootPath}>
            {props.title}
        </Link>
        <ul className="navbar-nav">
            {
                props.links.map((link, linkIndex) => (
                    <Link
                        className="navbar-brand"
                        to={link.path}
                        key={linkIndex}
                    >
                        {link.text}
                    </Link>
                ))
            }
        </ul>
    </nav>
);

// chapters/chapter_15/web/frontend/components/header.component.ts
/*
import { Component, Input } from "@angular/core";

type BgColor = "primary" | "secondary" | "success" |
               "danger" | "warning" | "info" | "light" |
               "dark" | "white";

@Component({
    selector: "",
    template: `
        <nav className={`navbar navbar-expand-lg navbar-light bg-${props.bg}`}>
        <Link className="navbar-brand" to={props.rootPath}>
            {props.title}
        </Link>
        <ul className="navbar-nav">
            {
                props.links.map((link, linkIndex) => (

                    <a className="navbar-brand" routerLink="link.path" routerLinkActive="active">
                        {link.text}
                    </a>
                ))
            }
        </ul>
    </nav>`
})
class Header {
    @Input() public bg!: BgColor;
    @Input() public title!: string;
    @Input() public rootPath!: string;
    @Input() public links!: { path: string; text: string }[];
}
*/
