// chapters/chapter_15/web/frontend/pages/homepage.component.ts
/*
import { Component } from "@angular/core";

@Component({
    selector: "home-page",
    template: `
    <Container>
        <Row>
            <Column width={6}>
                <Card
                    title="Movies"
                    description="Explore our database of movies"
                    linkPath="movies"
                    linkText="Movies"
                    img={null}
                />
            </Column>
            <Column width={6}>
                <Card
                    title="Actors"
                    description="Explore our actors of movies"
                    linkPath="actors"
                    linkText="Actors"
                    img={null}
                />
            </Column>
        </Row>
    </Container>
    `
})
export class HomePage {
    //
}
*/

// chapters/chapter_14/web/frontend/pages/home_page.tsx
import * as React from "react";
import { Card } from "../components/card_component";
import { Container, Row, Column } from "../components/grid_component";

export const HomePage = () => (
    <Container>
        <Row>
            <Column width={6}>
                <Card
                    title="Movies"
                    description="Explore our database of movies"
                    linkPath="/mobx_demo/movies"
                    linkText="Movies"
                    img={null}
                />
            </Column>
            <Column width={6}>
                <Card
                    title="Actors"
                    description="Explore our actors of movies"
                    linkPath="/mobx_demo/actors"
                    linkText="Actors"
                    img={null}
                />
            </Column>
        </Row>
    </Container>
);
