// chapters/chapter_15/web/frontend/components/button.component.ts
/*
import { Component, Input, Output, EventEmitter } from "@angular/core";

type Kind = "primary" | "secondary" | "success" |
            "danger" | "warning" | "info" | "light" |
            "dark" | "link";

@Component({
    selector: "app-button",
    template: `
        <button
            type="button"
            class={{btnClass}}
            (click)="click()"
        >
            <ng-content></ng-content>
        </button>`
})
export class Button {

    @Input() public kind?: Kind;
    @Input() public className?: string;
    @Output() public onClicked = new EventEmitter();

    public get btnClass(): string {
        if (this.className !== undefined) {
            return this.className;
        } else {
            const kind = this.kind ? this.kind : "primary";
            return `btn btn-${kind}`;
        }
    }

    public click() {
        this.onClicked.emit();
    }

}
*/

// chapters/chapter_14/web/frontend/components/button_component.tsx
import * as React from "react";

type Kind = "primary" | "secondary" | "success" |
            "danger" | "warning" | "info" | "light" |
            "dark" | "link";

interface ButtonProps {
    kind?: Kind;
    onClick(): void;
    className?: string;
}

export class Button extends React.Component<ButtonProps> {
    public render() {
        return (
            <button
                type="button"
                className={this._getClass()}
            >
                {this.props.children}
            </button>
        );
    }
    private _getClass() {
        if (this.props.className !== undefined) {
            // If a class is specified we use it
            return this.props.className;
        } else {
            // If no class is specified we use the default "btn" with kind "primary"
            // If a kind is specified we use it
            const kind = this.props.kind ? this.props.kind : "primary";
            return `btn btn-${kind}`;
        }
    }
}
