// chapters/chapter_15/web/frontend/components/listgroup.component.ts
import { Component, Input } from "@angular/core";

@Component({
    selector: "",
    template: `
    <ul className="list-group">
        if (this.props.error) {
            return <ErrorMsg msg={this.props.error.message} />;
        } else if (!this.props.items) {
            return <Loading />;
        } else {
            return this.props.items.map(
                (item, itemIndex) => (
                    <li className="list-group-item" key={itemIndex}>
                        {this.props.itemComponent(item)}
                    </li>
                )
            );
        }
    </ul>
    `
})
export class ListGroup {
    error: Error | null;
    items: any[] | null;
    itemComponent(item: any): JSX.Element;
}

// chapters/chapter_14/web/frontend/components/list_group_component.tsx
import * as React from "react";
import { ErrorMsg } from "./error_msg_component";
import { Loading } from "./loading_component";

interface ListGroupProps {
    error: Error | null;
    items: any[] | null;
    itemComponent(item: any): JSX.Element;
}

export class ListGroup extends React.Component<ListGroupProps> {
    public render() {
        return (
            <ul className="list-group">
                {this._renderItems()}
            </ul>
        );
    }
    private _renderItems() {
        if (this.props.error) {
            return <ErrorMsg msg={this.props.error.message} />;
        } else if (!this.props.items) {
            return <Loading />;
        } else {
            return this.props.items.map(
                (item) => (
                    <li className="list-group-item">
                        {this.props.itemComponent(item)}
                    </li>
                )
            );
        }
    }

}
